version: '3'

services:
  go-app:
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app
    command: >
      bash -c "
        go run ./server.go
      "
    ports:
      - "19999:8080"
