version: '3'

services:
  go-app:
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # - ./todo:/app
      - ./main:/app
    command: >
      bash -c "
        go run github.com/99designs/gqlgen generate &&
        go run ./server.go
      "
    ports:
      - "19999:8080"
